pipeline {
    agent { docker { image 'node:alpine' } }
    environment {
        HOME = '.'
    }
    stages {
        stage('Build') {
            steps {
                sh "npm install"
                sh "npm run build"
            }
        }
        stage('Deploy') {
            steps {
                dir('S10P22C208/frontend') {
                    // 리액트 컨테이너 중지
                    sh 'docker stop react-docker || true'
                    // 리액트 도커 컨테이너 제거
                    sh 'docker rm react-docker || true'
                    // 리액트 이미지 삭제
                    sh 'docker rmi react || true'

                    // 리액트 이미지 빌드(생성)
                    sh 'docker build -f Dockerfile -t react .' // backend/epilogue 들어가서 spring 이미지 생성

                    // 리액트 도커 컨테이너 실행
                    sh 'docker run -it -p 3000:80 -d --name react-docker react'
                }
            }
        }
    }
}
