pipeline {
    agent any

    stages {
        stage('Git Clone') {
            steps {
                // Git 저장소에서 소스 코드를 가져옵니다.
                git 'https://lab.ssafy.com/s10-blockchain-contract-sub2/S10P22C208.git'
            }
        }

        stage('Build') {
            steps {
                // Maven을 사용하여 Spring Boot 프로젝트를 빌드합니다.
                sh './gradlew clean build'
            }
        }
    }
}