pipeline {
    agent any

//     tools {
//         gradle 8.5
//     }

    stages {
        stage('Git Clone') {
            steps {
                // Git 저장소에서 소스 코드를 가져옵니다.
//                 git url: 'https://lab.ssafy.com/s10-blockchain-contract-sub2/S10P22C208.git',
//                     credentialsId: 'kn9012'
                echo 'Clone'
                git branch: 'backend', credentialsId: 'epilogue', url: 'https://lab.ssafy.com/s10-blockchain-contract-sub2/S10P22C208.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Build'
                // Maven을 사용하여 Spring Boot 프로젝트를 빌드합니다.
                sh './gradlew clean build'
            }
        }
    }
}